microservice-deploys:
  container:
    microserviceName: todos-api
    image: ronaldmiranda/todos-api
    tag: 47c54d2
    envs:
      normalEnvs:
        TODO_API_PORT: "8082"
        REDIS_CHANNEL: log_channel
        REDIS_HOST: redis-queue
        REDIS_PORT: "6379"
        ZIPKIN_URL: http://zipkin-svc.zipkin-system.svc.cluster.local:9411/api/v2/spans
      envsSecretRef:
        - ENV_NAME: JWT_SECRET
          SECRET_NAME: jwt-secret
          SECRET_KEY: token
  service:
    servicePort:
      - 8082
